Repository sw21-tug/Team_03, pull requests merged in 2021-06, with the labels that each got.

#84 [CR012] & [CR013] User profile & Account settings [GD,SM]
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/CocktailDetailActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/MainActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/UserProfileActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/serverAPI.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/ui/login/LoginActivity.kt
  Frontend/Android/app/src/main/res/layout/activity_user_profile.xml
  Frontend/Android/app/src/main/res/values-kv-rRU/strings.xml
  Frontend/Android/app/src/main/res/values/strings.xml
Labels: devtask

#85 CRA-CR021 adding ingredients implemented [SM, SB]
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/AddIngredientsActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/CocktailDetailActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/RatingDialog.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/dialogs/AddIngredientDialog.kt
  Frontend/Android/app/src/main/res/layout/ingrediants_dialog_addingrediant.xml
  Frontend/Android/app/src/main/res/layout/ingredients_dialog.xml
  Frontend/Android/app/src/main/res/values-kv-rRU/strings.xml
  Frontend/Android/app/src/main/res/values/strings.xml
Labels: devtask, user story

#86 [CR010] Drink recommendations [HM,SC]
  Frontend/Android/app/src/androidTest/java/com/team03/cocktailrecipesapp/ExampleInstrumentedTest.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/AddRecipeActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/CocktailDetailActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/MainActivity.kt
  Frontend/Android/app/src/main/res/layout/activity_cocktail_detail.xml
  Frontend/Android/app/src/main/res/layout/activity_main.xml
  Frontend/Android/app/src/main/res/layout/recommended_cocktail_list_card.xml
  Frontend/Android/app/src/main/res/layout/trending_cocktail_list_card.xml
Labels: user story

#92 CR022 modified translations and app layout [SD,GD]
  Frontend/Android/app/src/androidTest/java/com/team03/cocktailrecipesapp/ChangeLanguageTest.kt
  Frontend/Android/app/src/main/ic_launcher-playstore.png
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/AddRecipeActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/CocktailDetailActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/MainActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/SeeAllRecipiesActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/SharedPreferencesActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/UserProfileActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/dialogs/RatingDialog.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/ui/login/LoginActivity.kt
  Frontend/Android/app/src/main/res/drawable/ic_launcher_background.xml
  Frontend/Android/app/src/main/res/layout/activity_add_recipe.xml
  Frontend/Android/app/src/main/res/layout/activity_main.xml
  Frontend/Android/app/src/main/res/layout/activity_see_all_recipies.xml
  Frontend/Android/app/src/main/res/layout/activity_user_profile.xml
  Frontend/Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Frontend/Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Frontend/Android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Frontend/Android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  Frontend/Android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Frontend/Android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Frontend/Android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  Frontend/Android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Frontend/Android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Frontend/Android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  Frontend/Android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Frontend/Android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Frontend/Android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  Frontend/Android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Frontend/Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Frontend/Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  Frontend/Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Frontend/Android/app/src/main/res/values-kv-rRU/strings.xml
  Frontend/Android/app/src/main/res/values/colors.xml
  Frontend/Android/app/src/main/res/values/strings.xml
Labels: user story

#91 [CR024] Layout fix and initial test refactoring [HM,SC]
  Frontend/Android/app/src/androidTest/java/com/team03/cocktailrecipesapp/ChangeLanguageTest.kt
  Frontend/Android/app/src/androidTest/java/com/team03/cocktailrecipesapp/CocktailRecipesAppTest.kt
  Frontend/Android/app/src/androidTest/java/com/team03/cocktailrecipesapp/TestUtils.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/CocktailDetailActivity.kt
  Frontend/Android/app/src/main/res/layout/activity_cocktail_detail.xml
  Frontend/Android/app/src/main/res/values-kv-rRU/strings.xml
  Frontend/Android/app/src/main/res/values/strings.xml
Labels: devtask

#99 [DEV:FE-24]Fill db testcase[GD,KL] + [BUG02] fixing colors and list size [GD,SC]
  Frontend/Android/.idea/misc.xml
  Frontend/Android/app/src/androidTest/java/com/team03/cocktailrecipesapp/CocktailRecipesAppTest.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/AddRecipeActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/listener/GetRecipesListener.kt
  Frontend/Android/app/src/main/res/layout/activity_cocktail_detail.xml
  Frontend/Android/app/src/main/res/layout/activity_login.xml
  Frontend/Android/app/src/main/res/layout/activity_register.xml
  Frontend/Android/app/src/main/res/layout/activity_user_profile.xml
  Frontend/Android/app/src/main/res/layout/activity_user_settings.xml
  Frontend/Android/app/src/main/res/values/colors.xml
Labels: bug, devtask

#100 CR022 Cleaning cocktails detail page [SM,HM]
  Frontend/Android/.idea/misc.xml
  Frontend/Android/app/src/androidTest/java/com/team03/cocktailrecipesapp/CocktailRecipesAppTest.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/AddRecipeActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/CocktailDetailActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/ExpandableHeightListView.kt
  Frontend/Android/app/src/main/res/layout/activity_add_recipe.xml
  Frontend/Android/app/src/main/res/layout/activity_cocktail_detail.xml
Labels: devtask

#101 BUG01 fixed settings and logout view [SD,SB]
  Frontend/Android/app/src/main/AndroidManifest.xml
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/CocktailDetailActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/UserProfileActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/UserSettingsActivity.kt
  Frontend/Android/app/src/main/res/layout/activity_cocktail_detail.xml
  Frontend/Android/app/src/main/res/layout/activity_user_profile.xml
  Frontend/Android/app/src/main/res/layout/activity_user_settings.xml
  Frontend/Android/app/src/main/res/layout/cocktail_detail_ingrediant_card.xml
  Frontend/Android/app/src/main/res/values-kv-rRU/strings.xml
  Frontend/Android/app/src/main/res/values/strings.xml
Labels: bug

#102 [CR022] Clean app final refactoring [HM,SD]
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/AddRecipeActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/MainActivity.kt
  Frontend/Android/app/src/main/java/com/team03/cocktailrecipesapp/SharedPreferencesActivity.kt
  Frontend/Android/app/src/main/res/layout/activity_add_recipe.xml
  Frontend/Android/app/src/main/res/layout/activity_user_settings.xml
  Frontend/Android/app/src/main/res/values-kv-rRU/strings.xml
  Frontend/Android/app/src/main/res/values-round/strings.xml
  Frontend/Android/app/src/main/res/values/strings.xml
Labels: bug
